version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - backend
    expose:
      - "8081"
    depends_on:
      - mongodb

  flask-app:
    build: ./flask-app
    container_name: flask-app
    restart: always
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: webapp
      MONGO_USER: admin
      MONGO_PASS: password
    networks:
      - backend
    expose:
      - "5000"
    depends_on:
      - mongodb

  firewall:
    build: ./firewall
    container_name: firewall
    restart: always
    ports:
      - "80:80"
      - "8081:8081"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:

volumes:
  mongo_data:
