services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - web

  web:
    build: ./app
    networks:
      - backend
    environment:
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=boutique
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  frontend:
  backend:
